# Информация о приложении
app:
  # Номер версии сборки МС
  version: "0.0.1"

  # Название приложения
  name: "My Micro App"

  # Отображаемое имя сервиса
  displayName: "My Micro App Server"

  # Описание сервиса
  description: "My Micro App Server"

# Настройки логгирования
logging:
  # Уровень логгирования, варианты: debug, info, warning, error, fatal и panic
  level: "debug"

# Данные для инициализации сервиса
micro:
  # Данные для работы с реестром
  registry: "nats"
  registryAddress: "0.0.0.0:4222"

  # Данные для работы с брокером
  broker: "nats"
  brokerAddress: "0.0.0.0:4222"

  # Данные для работы с транспортом
  transport: "nats"
  transportAddress: "0.0.0.0:4222"

# Настройки подписки
subscrption:
  # Количество воркеров для разгребания очередей
  workers: 16
